
[2017-08-31 13:24:03] Traceback (most recent call last):
  File "v8function_handler.pyx", line 42, in cefpython_py35.V8FunctionHandler_Execute (cefpython_py35.cpp:96736)
  File "gui.py", line 27, in loadFile
    fname = filedialog.askopenfilename()
  File "/home/mwestphall/anaconda3/lib/python3.5/tkinter/filedialog.py", line 375, in askopenfilename
    return Open(**options).show()
  File "/home/mwestphall/anaconda3/lib/python3.5/tkinter/commondialog.py", line 48, in show
    s = w.tk.call(self.command, *w._options(self.options))
_tkinter.TclError: can't invoke "grab" command:  application has been destroyed


[2017-08-31 13:49:52] Traceback (most recent call last):
  File "v8function_handler.pyx", line 42, in cefpython_py35.V8FunctionHandler_Execute (cefpython_py35.cpp:96736)
  File "gui.py", line 55, in createPath
    region.findScanLines()
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 378, in findScanLines
    new_coords = sa.findScanLines()[1:-1]
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 214, in findScanLines
    self._width = self._spectrometer.swathWidthAt(self._alt)
  File "/home/mwestphall/MissionPlanner/AreaScanner/Spectrometer.py", line 28, in swathWidthAt
    return 2*alt*np.tan(np.radians(self.fieldOfView/2))
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'


[2017-08-31 13:53:29] Traceback (most recent call last):
  File "v8function_handler.pyx", line 42, in cefpython_py35.V8FunctionHandler_Execute (cefpython_py35.cpp:96736)
  File "gui.py", line 40, in setBearing
    self._bearing = float(bearing)
NameError: name 'bearing' is not defined


[2017-08-31 14:21:39] Traceback (most recent call last):
  File "v8function_handler.pyx", line 42, in cefpython_py35.V8FunctionHandler_Execute (cefpython_py35.cpp:96736)
  File "gui.py", line 49, in createPath
    region = ScanArea.ScanRegion.fromFile(self._fname)
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 442, in fromFile
    return FILE_FUNC_TREE[key][dtype](fname,home,**kwargs)
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 421, in fromKMLPoints
    raise NotImplementedError
NotImplementedError


[2017-08-31 14:23:43] Traceback (most recent call last):
  File "v8function_handler.pyx", line 42, in cefpython_py35.V8FunctionHandler_Execute (cefpython_py35.cpp:96736)
  File "gui.py", line 44, in loadFile
    fname = os.path.split(self._fname)[1]
  File "/home/mwestphall/anaconda3/lib/python3.5/posixpath.py", line 103, in split
    i = p.rfind(sep) + 1
AttributeError: 'tuple' object has no attribute 'rfind'


[2017-08-31 14:49:47] Traceback (most recent call last):
  File "v8function_handler.pyx", line 42, in cefpython_py35.V8FunctionHandler_Execute (cefpython_py35.cpp:96736)
  File "gui.py", line 58, in createPath
    bounds= region.boundBox
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 361, in boundBox
    NS = sorted(self._perimeter,key=lambda p:p['lat'])
AttributeError: 'ScanRegion' object has no attribute '_perimeter'


[2017-08-31 15:33:03] Traceback (most recent call last):
  File "v8function_handler.pyx", line 42, in cefpython_py35.V8FunctionHandler_Execute (cefpython_py35.cpp:96736)
  File "gui.py", line 55, in createPath
    region = ScanArea.ScanRegion.fromFile(self._fname)
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 454, in fromFile
    ext = os.path.splitext(fname)[1].lower()
  File "/home/mwestphall/anaconda3/lib/python3.5/posixpath.py", line 122, in splitext
    return genericpath._splitext(p, sep, None, extsep)
  File "/home/mwestphall/anaconda3/lib/python3.5/genericpath.py", line 118, in _splitext
    sepIndex = p.rfind(sep)
AttributeError: 'NoneType' object has no attribute 'rfind'


[2017-09-01 12:38:48] Traceback (most recent call last):
  File "v8function_handler.pyx", line 42, in cefpython_py35.V8FunctionHandler_Execute (cefpython_py35.cpp:96736)
  File "gui.py", line 62, in createPath
    coords = region.findScanLines()
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 392, in findScanLines
    self._reorderScanAreas()
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 386, in _reorderScanAreas
    self._scanareas.sort(key=_prox_to_home)
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 384, in _prox_to_home
    bb = a.boundBox()
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 131, in boundBox
    NS = sorted(points,key=lambda p:p['lat'])
NameError: name 'points' is not defined


[2017-09-01 12:39:24] Traceback (most recent call last):
  File "v8function_handler.pyx", line 42, in cefpython_py35.V8FunctionHandler_Execute (cefpython_py35.cpp:96736)
  File "gui.py", line 62, in createPath
    coords = region.findScanLines()
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 392, in findScanLines
    self._reorderScanAreas()
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 386, in _reorderScanAreas
    self._scanareas.sort(key=_prox_to_home)
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 384, in _prox_to_home
    bb = a.boundBox()
TypeError: 'list' object is not callable


[2017-09-01 12:39:52] Traceback (most recent call last):
  File "v8function_handler.pyx", line 42, in cefpython_py35.V8FunctionHandler_Execute (cefpython_py35.cpp:96736)
  File "gui.py", line 62, in createPath
    coords = region.findScanLines()
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 392, in findScanLines
    self._reorderScanAreas()
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 386, in _reorderScanAreas
    self._scanareas.sort(key=_prox_to_home)
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 385, in _prox_to_home
    return min(abs(bb[0]-self._home),abs(bb[1]-self.home))
TypeError: unsupported operand type(s) for -: 'dict' and 'dict'


[2017-09-01 12:41:12] Traceback (most recent call last):
  File "v8function_handler.pyx", line 42, in cefpython_py35.V8FunctionHandler_Execute (cefpython_py35.cpp:96736)
  File "gui.py", line 62, in createPath
    coords = region.findScanLines()
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 391, in findScanLines
    self._reorderScanAreas()
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 385, in _reorderScanAreas
    self._scanareas.sort(key=_prox_to_home)
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 384, in _prox_to_home
    return min(Edge(a.boundBox).distanceTo(self._home))
TypeError: __init__() missing 1 required positional argument: 'p2'


[2017-09-01 13:03:36] Traceback (most recent call last):
  File "v8function_handler.pyx", line 42, in cefpython_py35.V8FunctionHandler_Execute (cefpython_py35.cpp:96736)
  File "gui.py", line 56, in createPath
    region = ScanArea.ScanRegion.fromFile(self._fname,self._home)
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 457, in fromFile
    dtype=FILE_FUNC_TREE[key]['type'](fname)
  File "/home/mwestphall/MissionPlanner/AreaScanner/KMLParse.py", line 40, in findRegionType
    with open(kmlfile) as f:
FileNotFoundError: [Errno 2] No such file or directory: ''


[2017-09-01 15:35:02] Traceback (most recent call last):
  File "v8function_handler.pyx", line 42, in cefpython_py35.V8FunctionHandler_Execute (cefpython_py35.cpp:96736)
  File "gui.py", line 61, in createPath
    region = ScanArea.ScanRegion.from2DLatLonArray(coords,self._home)
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 414, in from2DLatLonArray
    home = home or coords[0][0]
NameError: name 'coords' is not defined


[2017-09-01 15:38:49] Traceback (most recent call last):
  File "v8function_handler.pyx", line 42, in cefpython_py35.V8FunctionHandler_Execute (cefpython_py35.cpp:96736)
  File "gui.py", line 63, in createPath
    region = ScanArea.ScanRegion.fromFile(self._fname,self._home)
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 461, in fromFile
    ext = os.path.splitext(fname)[1].lower()
  File "/home/mwestphall/anaconda3/lib/python3.5/posixpath.py", line 122, in splitext
    return genericpath._splitext(p, sep, None, extsep)
  File "/home/mwestphall/anaconda3/lib/python3.5/genericpath.py", line 118, in _splitext
    sepIndex = p.rfind(sep)
AttributeError: 'NoneType' object has no attribute 'rfind'


[2017-09-01 15:46:37] Traceback (most recent call last):
  File "v8function_handler.pyx", line 42, in cefpython_py35.V8FunctionHandler_Execute (cefpython_py35.cpp:96736)
  File "gui.py", line 63, in createPath
    region = ScanArea.ScanRegion.fromFile(self._fname,self._home)
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 461, in fromFile
    ext = os.path.splitext(fname)[1].lower()
  File "/home/mwestphall/anaconda3/lib/python3.5/posixpath.py", line 122, in splitext
    return genericpath._splitext(p, sep, None, extsep)
  File "/home/mwestphall/anaconda3/lib/python3.5/genericpath.py", line 118, in _splitext
    sepIndex = p.rfind(sep)
AttributeError: 'NoneType' object has no attribute 'rfind'


[2017-09-01 15:50:21] Traceback (most recent call last):
  File "v8function_handler.pyx", line 42, in cefpython_py35.V8FunctionHandler_Execute (cefpython_py35.cpp:96736)
  File "gui.py", line 63, in createPath
    region = ScanArea.ScanRegion.fromFile(self._fname,self._home)
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 461, in fromFile
    ext = os.path.splitext(fname)[1].lower()
  File "/home/mwestphall/anaconda3/lib/python3.5/posixpath.py", line 122, in splitext
    return genericpath._splitext(p, sep, None, extsep)
  File "/home/mwestphall/anaconda3/lib/python3.5/genericpath.py", line 118, in _splitext
    sepIndex = p.rfind(sep)
AttributeError: 'NoneType' object has no attribute 'rfind'


[2017-09-01 15:50:50] Traceback (most recent call last):
  File "v8function_handler.pyx", line 42, in cefpython_py35.V8FunctionHandler_Execute (cefpython_py35.cpp:96736)
  File "gui.py", line 55, in polygonizePoints
    area = ScanArea.ScanArea(points[0],points)
IndexError: list index out of range


[2017-09-01 15:51:37] Traceback (most recent call last):
  File "v8function_handler.pyx", line 42, in cefpython_py35.V8FunctionHandler_Execute (cefpython_py35.cpp:96736)
  File "gui.py", line 55, in polygonizePoints
    area = ScanArea.ScanArea(points[0],points)
IndexError: list index out of range


[2017-09-01 15:54:59] Traceback (most recent call last):
  File "v8function_handler.pyx", line 42, in cefpython_py35.V8FunctionHandler_Execute (cefpython_py35.cpp:96736)
  File "gui.py", line 63, in createPath
    region = ScanArea.ScanRegion.fromFile(self._fname,self._home)
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 461, in fromFile
    ext = os.path.splitext(fname)[1].lower()
  File "/home/mwestphall/anaconda3/lib/python3.5/posixpath.py", line 122, in splitext
    return genericpath._splitext(p, sep, None, extsep)
  File "/home/mwestphall/anaconda3/lib/python3.5/genericpath.py", line 118, in _splitext
    sepIndex = p.rfind(sep)
AttributeError: 'NoneType' object has no attribute 'rfind'


[2017-09-01 16:03:13] Traceback (most recent call last):
  File "v8function_handler.pyx", line 42, in cefpython_py35.V8FunctionHandler_Execute (cefpython_py35.cpp:96736)
  File "gui.py", line 63, in createPath
    region = ScanArea.ScanRegion.fromFile(self._fname,self._home)
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 461, in fromFile
    ext = os.path.splitext(fname)[1].lower()
  File "/home/mwestphall/anaconda3/lib/python3.5/posixpath.py", line 122, in splitext
    return genericpath._splitext(p, sep, None, extsep)
  File "/home/mwestphall/anaconda3/lib/python3.5/genericpath.py", line 118, in _splitext
    sepIndex = p.rfind(sep)
AttributeError: 'NoneType' object has no attribute 'rfind'


[2017-09-05 11:05:22] Traceback (most recent call last):
  File "v8function_handler.pyx", line 42, in cefpython_py35.V8FunctionHandler_Execute (cefpython_py35.cpp:96736)
  File "gui.py", line 63, in createPath
    region = ScanArea.ScanRegion.fromFile(self._fname,self._home)
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 461, in fromFile
    ext = os.path.splitext(fname)[1].lower()
  File "/home/mwestphall/anaconda3/lib/python3.5/posixpath.py", line 122, in splitext
    return genericpath._splitext(p, sep, None, extsep)
  File "/home/mwestphall/anaconda3/lib/python3.5/genericpath.py", line 118, in _splitext
    sepIndex = p.rfind(sep)
AttributeError: 'NoneType' object has no attribute 'rfind'


[2017-09-05 11:10:27] Traceback (most recent call last):
  File "v8function_handler.pyx", line 42, in cefpython_py35.V8FunctionHandler_Execute (cefpython_py35.cpp:96736)
  File "gui.py", line 63, in createPath
    region = ScanArea.ScanRegion.fromFile(self._fname,self._home)
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 461, in fromFile
    ext = os.path.splitext(fname)[1].lower()
  File "/home/mwestphall/anaconda3/lib/python3.5/posixpath.py", line 122, in splitext
    return genericpath._splitext(p, sep, None, extsep)
  File "/home/mwestphall/anaconda3/lib/python3.5/genericpath.py", line 118, in _splitext
    sepIndex = p.rfind(sep)
AttributeError: 'NoneType' object has no attribute 'rfind'


[2017-09-05 12:06:13] Traceback (most recent call last):
  File "v8function_handler.pyx", line 42, in cefpython_py35.V8FunctionHandler_Execute (cefpython_py35.cpp:96736)
  File "gui.py", line 63, in createPath
    region = ScanArea.ScanRegion.fromFile(self._fname,self._home)
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 461, in fromFile
    ext = os.path.splitext(fname)[1].lower()
  File "/home/mwestphall/anaconda3/lib/python3.5/posixpath.py", line 122, in splitext
    return genericpath._splitext(p, sep, None, extsep)
  File "/home/mwestphall/anaconda3/lib/python3.5/genericpath.py", line 118, in _splitext
    sepIndex = p.rfind(sep)
AttributeError: 'NoneType' object has no attribute 'rfind'


[2017-09-05 12:44:52] Traceback (most recent call last):
  File "v8function_handler.pyx", line 42, in cefpython_py35.V8FunctionHandler_Execute (cefpython_py35.cpp:96736)
  File "gui.py", line 74, in createPath
    dist = region.totalScanLength
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 406, in totalScanLength
    sum_dist+=llmath.distanceTo(self.coords[0],self.coords[-1])
AttributeError: 'ScanRegion' object has no attribute 'coords'


[2017-09-05 12:53:43] Traceback (most recent call last):
  File "v8function_handler.pyx", line 42, in cefpython_py35.V8FunctionHandler_Execute (cefpython_py35.cpp:96736)
  File "gui.py", line 45, in setBearing
    self._bearing = float(val)
ValueError: could not convert string to float: 


[2017-09-05 13:43:59] Traceback (most recent call last):
  File "v8function_handler.pyx", line 42, in cefpython_py35.V8FunctionHandler_Execute (cefpython_py35.cpp:96736)
  File "gui.py", line 39, in setAlt
    self._alt = float(val)
ValueError: could not convert string to float: 


[2017-09-05 13:46:41] Traceback (most recent call last):
  File "v8function_handler.pyx", line 42, in cefpython_py35.V8FunctionHandler_Execute (cefpython_py35.cpp:96736)
  File "gui.py", line 52, in getScanSpeed
    self._region._spectrometer.setFramePeriod(self._frame_pd)
AttributeError: 'External' object has no attribute '_frame_pd'


[2017-09-05 15:12:37] Traceback (most recent call last):
  File "v8function_handler.pyx", line 42, in cefpython_py35.V8FunctionHandler_Execute (cefpython_py35.cpp:96736)
  File "gui.py", line 77, in createPath
    region = ScanArea.ScanRegion.fromFile(self._fname,self._home)
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 479, in fromFile
    ext = os.path.splitext(fname)[1].lower()
  File "/home/mwestphall/anaconda3/lib/python3.5/posixpath.py", line 122, in splitext
    return genericpath._splitext(p, sep, None, extsep)
  File "/home/mwestphall/anaconda3/lib/python3.5/genericpath.py", line 118, in _splitext
    sepIndex = p.rfind(sep)
AttributeError: 'NoneType' object has no attribute 'rfind'


[2017-09-05 15:12:40] Traceback (most recent call last):
  File "v8function_handler.pyx", line 42, in cefpython_py35.V8FunctionHandler_Execute (cefpython_py35.cpp:96736)
  File "gui.py", line 77, in createPath
    region = ScanArea.ScanRegion.fromFile(self._fname,self._home)
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 479, in fromFile
    ext = os.path.splitext(fname)[1].lower()
  File "/home/mwestphall/anaconda3/lib/python3.5/posixpath.py", line 122, in splitext
    return genericpath._splitext(p, sep, None, extsep)
  File "/home/mwestphall/anaconda3/lib/python3.5/genericpath.py", line 118, in _splitext
    sepIndex = p.rfind(sep)
AttributeError: 'NoneType' object has no attribute 'rfind'


[2017-09-05 15:26:45] Traceback (most recent call last):
  File "v8function_handler.pyx", line 42, in cefpython_py35.V8FunctionHandler_Execute (cefpython_py35.cpp:96736)
  File "gui.py", line 81, in createPath
    scanner.setFramePeriod(self._scan_pd)
TypeError: setFramePeriod() missing 1 required positional argument: 'pd'


[2017-09-05 15:28:21] Traceback (most recent call last):
  File "v8function_handler.pyx", line 42, in cefpython_py35.V8FunctionHandler_Execute (cefpython_py35.cpp:96736)
  File "gui.py", line 52, in setSpectrometer
    self._spectrometer = Spectrometer.spectrometerByName(val)()
  File "/home/mwestphall/MissionPlanner/AreaScanner/Spectrometer.py", line 74, in spectrometerByName
    }[name]
KeyError: 'Norsk Elektro Optikk HySpex'


[2017-09-05 15:29:46] Traceback (most recent call last):
  File "v8function_handler.pyx", line 42, in cefpython_py35.V8FunctionHandler_Execute (cefpython_py35.cpp:96736)
  File "gui.py", line 77, in createPath
    region = ScanArea.ScanRegion.fromFile(self._fname,self._home)
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 479, in fromFile
    ext = os.path.splitext(fname)[1].lower()
  File "/home/mwestphall/anaconda3/lib/python3.5/posixpath.py", line 122, in splitext
    return genericpath._splitext(p, sep, None, extsep)
  File "/home/mwestphall/anaconda3/lib/python3.5/genericpath.py", line 118, in _splitext
    sepIndex = p.rfind(sep)
AttributeError: 'NoneType' object has no attribute 'rfind'


[2017-09-05 16:18:37] Traceback (most recent call last):
  File "v8function_handler.pyx", line 42, in cefpython_py35.V8FunctionHandler_Execute (cefpython_py35.cpp:96736)
  File "gui.py", line 94, in savePath
    self._region.toWayPoints(fname)
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 428, in toWayPoints
    self._coords,self._alt,self._bearing,speed)
  File "/home/mwestphall/MissionPlanner/AreaScanner/WaypointParse.py", line 18, in waypointsFromCoords
    with open(fname,'w') as f:
TypeError: invalid file: ()


[2017-09-05 16:20:23] Traceback (most recent call last):
  File "v8function_handler.pyx", line 42, in cefpython_py35.V8FunctionHandler_Execute (cefpython_py35.cpp:96736)
  File "gui.py", line 95, in savePath
    self._region.toWayPoints(fname)
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 428, in toWayPoints
    self._coords,self._alt,self._bearing,speed)
  File "/home/mwestphall/MissionPlanner/AreaScanner/WaypointParse.py", line 18, in waypointsFromCoords
    with open(fname,'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: ''


[2017-09-08 16:07:30] Traceback (most recent call last):
  File "v8function_handler.pyx", line 42, in cefpython_py35.V8FunctionHandler_Execute (cefpython_py35.cpp:96736)
  File "gui.py", line 86, in createPath
    coords = region.findScanLines()
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 479, in findScanLines
    new_coords = sa.findScanLines()[1:]
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 281, in findScanLines
    parallel_dir1,self._perimeter[2],first_point)[::first_traverse]
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 233, in _findIntersectionsInDirection
    key=lambda x:x.length)[-1]
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 233, in <lambda>
    key=lambda x:x.length)[-1]
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 42, in length
    self._length = llmath.distanceTo(self.start,self.end)
  File "/home/mwestphall/MissionPlanner/AreaScanner/LonLatMath.py", line 53, in distanceTo
    latr0 = radians(start['lat'])
TypeError: 'int' object is not subscriptable


[2017-09-10 17:24:13] Traceback (most recent call last):
  File "v8function_handler.pyx", line 42, in cefpython_py35.V8FunctionHandler_Execute (cefpython_py35.cpp:96736)
  File "gui.py", line 69, in polygonizePoints
    area = ScanArea.ScanArea(points[0],points)
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 103, in __init__
    self.setBearing(bearing)
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 137, in setBearing
    self._arrangePerimeter(self._perimeter)
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 169, in _arrangePerimeter
    self._center = self._computeCenter(perimeter)
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 162, in _computeCenter
    center = geometry.Polygon(coordlist).cetroid.coords
AttributeError: 'Polygon' object has no attribute 'cetroid'


[2017-09-10 17:25:10] Traceback (most recent call last):
  File "v8function_handler.pyx", line 42, in cefpython_py35.V8FunctionHandler_Execute (cefpython_py35.cpp:96736)
  File "gui.py", line 69, in polygonizePoints
    area = ScanArea.ScanArea(points[0],points)
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 103, in __init__
    self.setBearing(bearing)
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 137, in setBearing
    self._arrangePerimeter(self._perimeter)
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 169, in _arrangePerimeter
    self._center = self._computeCenter(perimeter)
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 163, in _computeCenter
    return {'lat':center[0],'lon':center[1]}
  File "/home/mwestphall/anaconda3/lib/python3.5/site-packages/shapely/coords.py", line 78, in __getitem__
    raise IndexError("index out of range")
IndexError: index out of range


[2017-09-10 17:26:14] Traceback (most recent call last):
  File "v8function_handler.pyx", line 42, in cefpython_py35.V8FunctionHandler_Execute (cefpython_py35.cpp:96736)
  File "gui.py", line 69, in polygonizePoints
    area = ScanArea.ScanArea(points[0],points)
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 103, in __init__
    self.setBearing(bearing)
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 137, in setBearing
    self._arrangePerimeter(self._perimeter)
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 170, in _arrangePerimeter
    self._center = self._computeCenter(perimeter)
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 164, in _computeCenter
    return {'lat':center[0],'lon':center[1]}
  File "/home/mwestphall/anaconda3/lib/python3.5/site-packages/shapely/coords.py", line 78, in __getitem__
    raise IndexError("index out of range")
IndexError: index out of range


[2017-09-13 12:04:42] Traceback (most recent call last):
  File "v8function_handler.pyx", line 42, in cefpython_py35.V8FunctionHandler_Execute (cefpython_py35.cpp:96736)
  File "gui.py", line 97, in savePath
    fname = filedialog.asksavefilename()
AttributeError: module 'tkinter.filedialog' has no attribute 'asksavefilename'


[2017-09-13 12:08:12] Traceback (most recent call last):
  File "v8function_handler.pyx", line 42, in cefpython_py35.V8FunctionHandler_Execute (cefpython_py35.cpp:96736)
  File "gui.py", line 102, in savePath
    self._region.toShapeFile(fname)
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 535, in toShapeFile
    self._coords,self.scanLineBoundBoxes,self._alt,speed)
  File "/home/mwestphall/MissionPlanner/AreaScanner/SHPParse.py", line 34, in flightPlanFromCoords
    for i in range(len(coords)/4):
TypeError: 'float' object cannot be interpreted as an integer


[2017-09-13 12:08:55] Traceback (most recent call last):
  File "v8function_handler.pyx", line 42, in cefpython_py35.V8FunctionHandler_Execute (cefpython_py35.cpp:96736)
  File "gui.py", line 102, in savePath
    self._region.toShapeFile(fname)
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 535, in toShapeFile
    self._coords,self.scanLineBoundBoxes,self._alt,speed)
  File "/home/mwestphall/MissionPlanner/AreaScanner/SHPParse.py", line 39, in flightPlanFromCoords
    bounds = coordDictListToCoord2DList(scanlinebounds[i],0)
  File "/home/mwestphall/MissionPlanner/AreaScanner/SHPParse.py", line 30, in coordDictListToCoord2DList
    return map(coord_dict_list,lambda c:[c['lon'],c['lat'],alt])
TypeError: 'function' object is not iterable


[2017-09-13 12:12:03] Traceback (most recent call last):
  File "v8function_handler.pyx", line 42, in cefpython_py35.V8FunctionHandler_Execute (cefpython_py35.cpp:96736)
  File "gui.py", line 102, in savePath
    self._region.toShapeFile(fname)
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 535, in toShapeFile
    self._coords,self.scanLineBoundBoxes,self._alt,speed)
  File "/home/mwestphall/MissionPlanner/AreaScanner/SHPParse.py", line 40, in flightPlanFromCoords
    w.poly(parts=bounds)
NameError: name 'w' is not defined


[2017-09-13 12:12:59] Traceback (most recent call last):
  File "v8function_handler.pyx", line 42, in cefpython_py35.V8FunctionHandler_Execute (cefpython_py35.cpp:96736)
  File "gui.py", line 102, in savePath
    self._region.toShapeFile(fname)
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 535, in toShapeFile
    self._coords,self.scanLineBoundBoxes,self._alt,speed)
  File "/home/mwestphall/MissionPlanner/AreaScanner/SHPParse.py", line 43, in flightPlanFromCoords
    writer.poly(parts=line,shapeType=shapefile.POLYLINE)
  File "/home/mwestphall/anaconda3/lib/python3.5/site-packages/shapefile.py", line 1036, in poly
    point = list(point)
TypeError: 'numpy.float64' object is not iterable


[2017-09-13 13:58:50] Traceback (most recent call last):
  File "shapely/speedups/_speedups.pyx", line 231, in shapely.speedups._speedups.geos_linearring_from_py
AttributeError: 'list' object has no attribute '__array_interface__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "v8function_handler.pyx", line 42, in cefpython_py35.V8FunctionHandler_Execute (cefpython_py35.cpp:96736)
  File "gui.py", line 74, in centerOfPoints
    area = ScanArea.ScanArea(points[0],points)
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 103, in __init__
    self.setBearing(bearing)
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 137, in setBearing
    self._arrangePerimeter(self._perimeter)
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 170, in _arrangePerimeter
    self._center = self._computeCenter(perimeter)
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 162, in _computeCenter
    center = geometry.Polygon(coordlist).centroid.coords
  File "/home/mwestphall/anaconda3/lib/python3.5/site-packages/shapely/geometry/polygon.py", line 231, in __init__
    ret = geos_polygon_from_py(shell, holes)
  File "/home/mwestphall/anaconda3/lib/python3.5/site-packages/shapely/geometry/polygon.py", line 483, in geos_polygon_from_py
    ret = geos_linearring_from_py(shell)
  File "shapely/speedups/_speedups.pyx", line 318, in shapely.speedups._speedups.geos_linearring_from_py
ValueError: A LinearRing must have at least 3 coordinate tuples


[2017-09-13 13:59:32] Traceback (most recent call last):
  File "shapely/speedups/_speedups.pyx", line 231, in shapely.speedups._speedups.geos_linearring_from_py
AttributeError: 'list' object has no attribute '__array_interface__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "v8function_handler.pyx", line 42, in cefpython_py35.V8FunctionHandler_Execute (cefpython_py35.cpp:96736)
  File "gui.py", line 74, in centerOfPoints
    area = ScanArea.ScanArea(points[0],points)
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 103, in __init__
    self.setBearing(bearing)
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 137, in setBearing
    self._arrangePerimeter(self._perimeter)
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 170, in _arrangePerimeter
    self._center = self._computeCenter(perimeter)
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 162, in _computeCenter
    center = geometry.Polygon(coordlist).centroid.coords
  File "/home/mwestphall/anaconda3/lib/python3.5/site-packages/shapely/geometry/polygon.py", line 231, in __init__
    ret = geos_polygon_from_py(shell, holes)
  File "/home/mwestphall/anaconda3/lib/python3.5/site-packages/shapely/geometry/polygon.py", line 483, in geos_polygon_from_py
    ret = geos_linearring_from_py(shell)
  File "shapely/speedups/_speedups.pyx", line 318, in shapely.speedups._speedups.geos_linearring_from_py
ValueError: A LinearRing must have at least 3 coordinate tuples


[2017-09-13 14:00:18] Traceback (most recent call last):
  File "v8function_handler.pyx", line 42, in cefpython_py35.V8FunctionHandler_Execute (cefpython_py35.cpp:96736)
  File "gui.py", line 75, in centerOfPoints
    js_callback.call(area._center,self.noop)
AttributeError: 'cefpython_py35.JavascriptCallback' object has no attribute 'call'


[2017-09-13 14:07:20] Traceback (most recent call last):
  File "v8function_handler.pyx", line 42, in cefpython_py35.V8FunctionHandler_Execute (cefpython_py35.cpp:96736)
  File "gui.py", line 81, in createPath
    region = ScanArea.ScanRegion.fromFile(self._fname,self._home)
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 587, in fromFile
    ext = os.path.splitext(fname)[1].lower()
  File "/home/mwestphall/anaconda3/lib/python3.5/posixpath.py", line 122, in splitext
    return genericpath._splitext(p, sep, None, extsep)
  File "/home/mwestphall/anaconda3/lib/python3.5/genericpath.py", line 118, in _splitext
    sepIndex = p.rfind(sep)
AttributeError: 'NoneType' object has no attribute 'rfind'


[2017-09-13 14:07:57] Traceback (most recent call last):
  File "v8function_handler.pyx", line 42, in cefpython_py35.V8FunctionHandler_Execute (cefpython_py35.cpp:96736)
  File "gui.py", line 90, in createPath
    coords = region.findScanLines()
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 482, in findScanLines
    new_coords = sa.findScanLines()[1:]
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 290, in findScanLines
    parallel_dir2,self._coords[-1],first_point)
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 236, in _findIntersectionsInDirection
    key=lambda x:x.length)[-1]
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 236, in <lambda>
    key=lambda x:x.length)[-1]
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 43, in length
    self._length = llmath.distanceTo(self.start,self.end)
  File "/home/mwestphall/MissionPlanner/AreaScanner/LonLatMath.py", line 53, in distanceTo
    latr0 = radians(start['lat'])
TypeError: 'int' object is not subscriptable


[2017-09-13 14:25:42] Traceback (most recent call last):
  File "v8function_handler.pyx", line 42, in cefpython_py35.V8FunctionHandler_Execute (cefpython_py35.cpp:96736)
  File "gui.py", line 90, in createPath
    coords = region.findScanLines()
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 482, in findScanLines
    new_coords = sa.findScanLines()[1:]
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 284, in findScanLines
    parallel_dir1,self._perimeter[2],first_point)[::first_traverse]
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 236, in _findIntersectionsInDirection
    key=lambda x:x.length)[-1]
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 236, in <lambda>
    key=lambda x:x.length)[-1]
  File "/home/mwestphall/MissionPlanner/AreaScanner/ScanArea.py", line 43, in length
    self._length = llmath.distanceTo(self.start,self.end)
  File "/home/mwestphall/MissionPlanner/AreaScanner/LonLatMath.py", line 53, in distanceTo
    latr0 = radians(start['lat'])
TypeError: 'int' object is not subscriptable

